### PR TITLE
Add source_cidr_blocks variable

### PR DESCRIPTION
**Pull request by mkmarek**

### CODE REVIEW

**Review by mikael-lindstrom — APPROVED** [review]
LGTM 👍

**Comment by mkmarek** [comment]
Can someone merge this? It seems I don't have the rights to do so.

**Comment by mhd999** [comment]
One thought regarding this PR, seems we can use the `cidr_blocks` in `aws_security_group_rule`  to allow traffic from `vpc`.

**Review by itsdalmo — COMMENTED** [review]
Couple of things...

Right now we are creating security groups inside the module for any resource that supports it; how we do it varies a lot however, and this is yet another approach as far as I can tell:
1. In the autoscaling and ecs/cluster modules we set egress all and nothing else.
2. For Lambda we just create the SG and nothing else.
3. Now for this, we'll be accepting a list of CIDR blocks for which we allow ingress.
4. ???
4. I think we should be consistent...

Either way I think we should use source security group ID's instead of CIDR blocks to allow ingress, unless we want clients to talk directly with the cache layer?

**Comment by mkmarek** [comment]
I think the better solution s number 2. so I updated it to be at least consistent with the lambda approach.

Our scenario is that we want to allow multiple lambda functions to access one elasticache which isn't yet possible with this module. So id it would output its security group id then we could work with that defining our own rules.

**Review by mikael-lindstrom — APPROVED** [review]
LGTM 👍

**Comment by itsdalmo** [comment]
Seems this one has gone stale @mkmarek - do you still want to merge this or?

**Comment by mkmarek** [comment]
Yes, please. We're currently using my fork in order to use this module.

**Comment by itsdalmo** [comment]
Released this as [v1.1.0](https://github.com/telia-oss/terraform-aws-elasticache/releases/tag/v1.1.0) (breaking change, but semantic versioning for terraform is hard 😅).

**Pull request merged**
